name: Asset update
on:
    push:
        branches:
            - master

permissions:
    contents: read

jobs:
    master:
        name: Push to main
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: WordPress.org asset update
              uses: 10up/action-wordpress-plugin-asset-update@stable
              env:
                  SLUG: ${{ secrets.SLUG }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  README_NAME: readme.md
